### ISSUE TITLE
Apply scripts and snippets without reloading Obsidian

### ISSUE THREAD

**Issue by mnowotnik** [mnowotnik/obsidian-user-plugins#1]

**Comment by vanadium23** [comment]
I think hot-reload plugin can help, at least as an inspiration.
https://github.com/pjeby/hot-reload

**Comment by mnowotnik** [comment]
@vanadium23  Sure, thanks. I'll probably add this improvement next week.

**Comment by mnowotnik** [comment]
Closed via fd65651a8
