### ISSUE TITLE
Not working here

### ISSUE THREAD

**Issue by jpsala** [mnowotnik/obsidian-user-plugins#2]
Hello here, I tried the plugin, first I installed it within obsidian, and then I cloned it, the two times it installed correctly but it's not loading the scripts, not the ones in the options/snipper nor the ones in the scripts folder, no errors, just copied/pasted the snippets from the docs.

**Comment by mnowotnik** [comment]
Hi, 
Could you tell me obsidian version and your system?

**Comment by mnowotnik** [comment]
@jpsala can't replicate. You need to click Run snippet button or enable a script file. There is a bug however that causes additional commands to be overwritten.

**Comment by mnowotnik** [comment]
Can't reproduce

**Comment by ghost** [comment]
I had some problems as well but then I noticed that the snippet example and the script file example are missing the "**addCommand**" "**id**".
