### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by NomarCub** [mnowotnik/obsidian-user-plugins#6]
The auto-update feature in Obsidian lists a new update for this plugin, but fails to update it, as the new version is only present in metadata, not as a release.

**Comment by mnowotnik** [comment]
Oh, I thought it's on tag push. Will fix today. Thanks for heads-up.

**Comment by mnowotnik** [comment]
Should be good now. Can you check?

**Comment by NomarCub** [comment]
All good, thank you!
When do you plan on releasing a new version by the way?

**Comment by mnowotnik** [comment]
This weekend probably
